- name: Install a list of packages
  hosts: all
  become: true
  tasks:
    - name: Install ruby and bundler
      apt:
        name: "{{ packages }}"
        update_cache: yes
        state: latest
      vars:
        packages:
        - ruby-full 
        - ruby-bundler 
        - build-essential
